# dont need to do anything to this.
locations:
  min:
    x: -50
    y: 0
    z: -50
    world: world
  max:
    x: 50
    y: 256
    z: 50
    world: world

scoreboard:
  lobby:
    title: "&cLav Yükseliyor"
    lines:
      - ""
      - "You:"
      - "» %player%"
      - "Time Left:"
      - "» %time_left%"
      - ""
  game:
    title: "&cLav Yükseliyor"
    lines:
      - ""
      - "You:"
      - "» %player%"
      - "Time Left:"
      - "» %time_left%"
      - "Kills:"
      - "» %player_kills%"
      - ""