# dont need to do anything to this.
locations:
  size: 100
  min:
    x: -50
    y: 0
    z: -50
    world: world
  max:
    x: 50
    y: 256
    z: 50
    world: world

messages:
  prefix: "&7[&eTFIL&7] &8» "
  lava-started-rising: "&cLava has started rising!"

scoreboard:
  lobby:
    title: "&cLav Yükseliyor"
    lines:
      - ""
      - "You:"
      - "» %player%"
      - "Time Left:"
      - "» %time_left%"
      - ""
  game:
    title: "&cLav Yükseliyor"
    lines:
      - ""
      - "You:"
      - "» %player%"
      - "Time Left:"
      - "» %time_left%"
      - "Kills:"
      - "» %player_kills%"
      - ""

lava-place-timer: 3
lava-fast-paced-block-amount: 3
